networks:
  monopoly:
    driver: bridge

services:
  postgres:
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    image: postgres:16-alpine
    networks:
      - monopoly
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - monopoly_db_postgres:/var/lib/postgresql/data

volumes:
  monopoly_db_postgres:
